application:
  name: auth-service

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: auth-service

server:
  port: 8080

